
package soap.rank;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GameRankService", targetNamespace = "http://rank.soap/", wsdlLocation = "http://localhost:8082/rank/rank?wsdl")
public class GameRankService
    extends Service
{

    private final static URL GAMERANKSERVICE_WSDL_LOCATION;
    private final static WebServiceException GAMERANKSERVICE_EXCEPTION;
    private final static QName GAMERANKSERVICE_QNAME = new QName("http://rank.soap/", "GameRankService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/rank/rank?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GAMERANKSERVICE_WSDL_LOCATION = url;
        GAMERANKSERVICE_EXCEPTION = e;
    }

    public GameRankService() {
        super(__getWsdlLocation(), GAMERANKSERVICE_QNAME);
    }

    public GameRankService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GAMERANKSERVICE_QNAME, features);
    }

    public GameRankService(URL wsdlLocation) {
        super(wsdlLocation, GAMERANKSERVICE_QNAME);
    }

    public GameRankService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GAMERANKSERVICE_QNAME, features);
    }

    public GameRankService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GameRankService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Rank
     */
    @WebEndpoint(name = "GameRankPort")
    public Rank getGameRankPort() {
        return super.getPort(new QName("http://rank.soap/", "GameRankPort"), Rank.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Rank
     */
    @WebEndpoint(name = "GameRankPort")
    public Rank getGameRankPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rank.soap/", "GameRankPort"), Rank.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GAMERANKSERVICE_EXCEPTION!= null) {
            throw GAMERANKSERVICE_EXCEPTION;
        }
        return GAMERANKSERVICE_WSDL_LOCATION;
    }

}
