
package soap.rank;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Rank", targetNamespace = "http://rank.soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Rank {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateLoseArchive", targetNamespace = "http://rank.soap/", className = "soap.rank.UpdateLoseArchive")
    @ResponseWrapper(localName = "updateLoseArchiveResponse", targetNamespace = "http://rank.soap/", className = "soap.rank.UpdateLoseArchiveResponse")
    @Action(input = "http://rank.soap/Rank/updateLoseArchiveRequest", output = "http://rank.soap/Rank/updateLoseArchiveResponse")
    public int updateLoseArchive(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNewUser", targetNamespace = "http://rank.soap/", className = "soap.rank.GetNewUser")
    @ResponseWrapper(localName = "getNewUserResponse", targetNamespace = "http://rank.soap/", className = "soap.rank.GetNewUserResponse")
    @Action(input = "http://rank.soap/Rank/getNewUserRequest", output = "http://rank.soap/Rank/getNewUserResponse")
    public String getNewUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createRank", targetNamespace = "http://rank.soap/", className = "soap.rank.CreateRank")
    @ResponseWrapper(localName = "createRankResponse", targetNamespace = "http://rank.soap/", className = "soap.rank.CreateRankResponse")
    @Action(input = "http://rank.soap/Rank/createRankRequest", output = "http://rank.soap/Rank/createRankResponse")
    public List<String> createRank();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateWinArchive", targetNamespace = "http://rank.soap/", className = "soap.rank.UpdateWinArchive")
    @ResponseWrapper(localName = "updateWinArchiveResponse", targetNamespace = "http://rank.soap/", className = "soap.rank.UpdateWinArchiveResponse")
    @Action(input = "http://rank.soap/Rank/updateWinArchiveRequest", output = "http://rank.soap/Rank/updateWinArchiveResponse")
    public int updateWinArchive(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
